typography_spectrum: 0.4610333962042327
content_rating:
  adult: false
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.9250565447095819
  lightness: 0.10577128426826532
  saturation: 0.4750449804886991
  rhythmicContrast: 0.06919471551793267
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.9120343809098116
author: {}
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/223aa791-81fc-45a1-adf4-3faac51c2ebd.jpg
name: JetSetFm
navigation:
  - name: Listen Live
    id: 287efcc8-fa6f-424a-b019-c71c3f054c12
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c45f171-fa26-4f44-a77f-9b2243c2a1eb.jpg
title: We Make You Move
content: []
coverPrefs:
  filter: false
description: Open Format Radio 24/7
purpose:
  - type: external
    label: Listen Live Now
    url: 'http://www.streamlicensing.com/play/player.php?sid=1641&stream_id=2777'
  - type: contact
    label: JetSet Staff
    url: 'mailto:jetsetfm@gmail.com'
